# DEFAULT
spring:
  profiles:
    active: default
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS TTEXECUTER;
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changes/db.changelog.xml
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK
---
#TEST


